version: 1.0.{build}
init:
  - cmd: if defined APPVEYOR_PULL_REQUEST_NUMBER appveyor exit
  - git config --global core.autocrlf true
image: Visual Studio 2019
services:
  - mssql2017
  - mysql
  - postgresql101
 
cache:
  - '%USERPROFILE%\.nuget\packages -> **\*.csproj'

before_build:
- ps: "Add-Content c:\\mongodb\\mongod.cfg \"`r`nreplication:`r`n  replSetName: rs0`r`n\""
- cmd: "net start mongodb"
- cmd: "c:\\mongodb\\bin\\mongo --eval \"printjson(rs.initiate())\""
- choco install rabbitmq

build_script:
  - PS: "echo \"BuildFolder Is:$APPVEYOR_BUILD_FOLDER\""
  - ps:  Invoke-WebRequest "https://github.com/tesseract-ocr/tessdata/raw/master/eng.traineddata" -OutFile data/tessdata/eng.traineddata
  - ps: Remove-Item "./tests/common/Smi.Common.Tests/TestDatabases.txt"
  - ps: Rename-Item -Path "./tests/common/Smi.Common.Tests/TestDatabases.appveyor.txt" -NewName "TestDatabases.txt"
    
  - ps: Remove-Item "./tests/common/Smi.Common.Tests/RelationalDatabases.yaml"
  - ps: Rename-Item -Path "./tests/common/Smi.Common.Tests/RelationalDatabases.appveyor.yaml" -NewName "RelationalDatabases.yaml"
  
  - ps: "[Net.ServicePointManager]::SecurityProtocol = \"tls12, tls11, tls\""
  - ps: "New-Item -Path \".\" -Name \"rdmp-cli\" -ItemType \"directory\""
  - ps:  Invoke-WebRequest https://github.com/HicServices/RDMP/releases/download/v4.1.1/rdmp-cli-win-x64.zip -OutFile rdmp-cli-win-x64.zip
  
  
  - ps: 7z x rdmp-cli-win-x64.zip -oC:\projects\smiservices\rdmp-cli
  - ps: C:\projects\smiservices\rdmp-cli\rdmp.exe install localhost\SQL2017 TEST_ -D -u sa -p Password12!
 
  - cmd: "\"c:/program files/dotnet/dotnet.exe\" test ./tests/run-all-tests.proj -c Release -p:BuildInParallel=false"

test: off
